### ISSUE TITLE
벡터 스킨 하단 푸터 '권리침해신고' 부분 누락

### ISSUE THREAD

**Issue by vvvvviral** [femiwiki/docker-mediawiki#101]
페미위키 스킨에서는 정상적으로 출력되나, 미디어위키 기본 벡터 스킨 하단 푸터에서는 '권리침해신고' 부분이 누락되었다는 제보가 있습니다.

**Comment by choidamdam** [comment]
배포 완료:
https://github.com/femiwiki/femiwiki.com/releases/tag/20180428-r1
