### ISSUE TITLE
파일 업로드 용량 2MB에서 10MB로 올리기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#110]
[주제:U6h99b1qshyumh3r](https://femiwiki.com/w/%EC%A3%BC%EC%A0%9C:U6h99b1qshyumh3r)에서 요청되었고 회의에서 10mb로 올리기로 결정되었다고 합니다([공개된 회의록 링크](https://docs.google.com/document/d/1qRKaAVKtFmo2vHfpxoIFP-MbOLLOxeh8vSwq9aZ1y-c/edit?usp=sharing))

**Comment by lens0021** [comment]
https://femiwiki.com/w/페미위키:업데이트#20180429-r1

**Comment by simnalamburt** [comment]
용량 늘리는법

```console
$ sudo vim /etc/php/7.0/apache2/php.ini
post_max_size = 10M
upload_max_filesize = 10M

$ sudo service apache2 reload
```
