### ISSUE TITLE
위키 Admin 계정 패스워드 설정

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#12]
위키 설치 직후 Admin 계정 패스워드가 뭔지 알 수 없습니다. 혹시 아래 라인에 --pass "$"이라는 부분이 -pass "$4"가 맞지 않나요?
https://github.com/femiwiki/femiwiki.com/blob/92e14394ffb2404fc192b09af8f616ab6a47da0b/www/provision.sh#L111

**Comment by revi** [comment]
$ 부분에는 실제로 사용하는 비밀번호를 집어넣는 것이기 때문에 공개되는 스크립트에는 어느 값을 집어넣든 무방할 것 같습니다.

**Comment by lens0021** [comment]
femiwiki.com/www/[provision.sh](https://github.com/femiwiki/femiwiki.com/blob/92e14394ffb2404fc192b09af8f616ab6a47da0b/www/provision.sh) 파일을 호출하는 아래 커맨드의 강조된 부분을 받아들이려면 다른 `$1`~`$3`와 동일하게 `$4`로 적는 것이 맞지 않나요?

> c.vm.provision "shell", path: "./www/provision.sh", args: "#{DEV_PROTOCOL} #{DEV_HOST} #{DEV_PARSOID} #{**ENV['ADMIN_PW'**]}" ([femiwiki.com/Vagrantfile의 13번째 열](https://github.com/femiwiki/femiwiki.com/blob/92e14394ffb2404fc192b09af8f616ab6a47da0b/Vagrantfile#L13))
