### ISSUE TITLE
[[특:통계]]의 문서 집계 방법 변경

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#127]
현재 링크가 있는 문서만 집계되는데, 그냥 모든 문서를 집계되게 하는 것이 [위키에서 요청](https://femiwiki.com/index.php?title=%EC%A3%BC%EC%A0%9C:Ud7fqimo4u1tz21j&topic_showPostId=ud7ue8k5yp3c328n#flow-post-ud7ue8k5yp3c328n)되었습니다.

**Comment by choidamdam** [comment]
배포 완료:
https://github.com/femiwiki/femiwiki.com/releases/tag/20180519-r1
