### ISSUE TITLE
확장 기능과 스킨 분리

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#134]
https://github.com/femiwiki/skin 과 https://github.com/femiwiki/Sanctions 의 파일들이 이 repo에 직접 포함되어 있어 사실상 중복되어 있고 다른 repo는 관리가 안 되는 것 같은데 서브 모듈로 교체하면 어떨까요?

**Comment by simnalamburt** [comment]
서브모듈로 교체하는것은 좋은데, 그러려면 배포하는방법이 달라져야해서 @choidamdam 님께서 조심하셔야할 것 같습니다.

그리고 서브모듈로 분리하실때에 가급적이면 https://github.com/femiwiki/femiwiki.com/tree/master/www/skins/Femiwiki 와 https://github.com/femiwiki/skin/tree/master/Femiwiki 양쪽의 커밋 히스토리가 모두 다 남게 해주시면 좋을 것 같은데..

@lens0021 한번 시도해주세요. 어려우시면 제가 직접할게요. 아래 두 글에 하는법 있어요.

###### References
- https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/
- https://help.github.com/articles/about-git-subtree-merges/

**Comment by lens0021** [comment]
분리를 하였습니다. 그런데, repository 안에서 커밋 히스토리를 볼 때는 내역이 나오지만 각 파일의 history를 보면 나오지 않습니다, 무언가 잘못 한 것 같습니다 :-(

이슈는 스킨에 관련해 보이는 것들을 https://github-issue-mover.appspot.com/ 을 이용해서 옮겼습니다.

**Comment by simnalamburt** [comment]
분리 어떻게 하셨나요?

**Comment by lens0021** [comment]
```bash
# femiwiki/femiwiki.com를 클론하여 다음을 실행했습니다
git filter-branch --prune-empty --subdirectory-filter www/skins/Femiwiki master

# Github에서 Femiwiki/skin-master라는 빈 Repo를 만들고
# 위 디렉토리에서 origin으로 설정하고 push했습니다
git remote set-url origin git@github.com:femiwiki/skin-master.git
git push -u origin master

# femiwiki/skin을 클론하여 다음을 실행했습니다
git remote add -f skin-master git@github.com:femiwiki/skin-master.git
git merge -X theirs --no-commit --allow-unrelated-histories skin-master/master
git read-tree --prefix=skin-master/ -u skin-master/master
rm -rf images/ resources/ i18n/
mv skin-master/* .
mv skin-master/.* .
rm -rf skin-master/
git commit -m"subtree merged"
git push
```

한 번 중간에 revert한적이 있었는데 위에서는 생략했습니다

**Comment by simnalamburt** [comment]
```
mv skin-master/* .
mv skin-master/.* .
```

이게 원인같아요

**Comment by simnalamburt** [comment]
커밋 히스토리 잘 바꿔서 https://github.com/femiwiki/skin 의 마스터 브랜치에 푸시해뒀고, 옛날 커밋로그는 `master-old` 브랜치에 놨습니다.

**Comment by simnalamburt** [comment]
해결끝

**Comment by lens0021** [comment]
지금 있는 다른 확장기능도 분리하겠읍니다~ 😁
