### ISSUE TITLE
모듈토론에 플로우 미적용

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#17]
죄송합니다, https://github.com/femiwiki/femiwiki.com/blob/master/www/LocalSettings.php#L248 근처에
`$wgNamespaceContentModels[NS_MODULE_TALK] = 'flow-board';`을 빼먹었습니다.;; 혹시 수정 가능할까요?

**Comment by suyooktang** [comment]
죄송하긴요. 감사하지요. 방금 추가했어요 :)

**Comment by lens0021** [comment]
@suyooktang 거듭죄송합니다ㅠㅠ 혹시 플로우 관련 명령(238-249행)을 스크리분토(251-253행)보다 아래로 내려주실 수 있을까요? NS_MODULE_TALK라는 변수가 선언되기 전인지 적용이 안되네요ㅠㅠ

**Comment by suyooktang** [comment]
올렸습니다 :)
