### ISSUE TITLE
LocalisationUpdate Extension 사용

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#216]
### 요약

[Extension:LocalisationUpdate](https://www.mediawiki.org/wiki/Extension:LocalisationUpdate)는 미디어위키 내 시스템 메시지들을 네티즌들이 [translatewiki](https://translatewiki.net)에서 실시간으로 번역한 최신 판본(을 위키미디어에서 관리하는 repository로 봇이 옮긴 것)으로 업데이트해주는 기능을 제공합니다.

그러나 [문제](https://phabricator.wikimedia.org/T176390)가 있어서 미디어위키 1.32 전까지는 사용이 불가하여 시간이 소요되었고, 그 이후에 [다른 문제](https://phabricator.wikimedia.org/T237435) 역시 있어서 1.35 전까진 사용이 불가하지만 이를 패치한 포크를 사용하여 적용할 예정입니다.

#### 점검
- [x] ~~1.32 릴리즈 기다리기~~
- [x] ~~[1.32 업그레이드](https://github.com/femiwiki/mediawiki/issues/250)~~
- [x] 패치 적용한 사용 가능한 버전의 포크 만들기 &rarr; https://github.com/femiwiki/femiwiki/issues/114
- [x] 크론 사용 &rarr; https://github.com/femiwiki/mediawiki/commit/b712572
- [x] 작동 확인(`/tmp/cache/*.json`이 생성되었는지 확인)
- [x] 크론 로그 확인
- [x] [페미위키:잘못된 메시지 문서](https://femiwiki.com/w/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%EC%9E%98%EB%AA%BB%EB%90%9C_%EB%A9%94%EC%8B%9C%EC%A7%80) 보존 처리
- [x] [특수:모든메시지에서 수정된 메시지](https://femiwiki.com/index.php?title=%ED%8A%B9%EC%88%98%3A%EB%AA%A8%EB%93%A0%EB%A9%94%EC%8B%9C%EC%A7%80&prefix=&filter=modified&lang=ko&limit=100) 중 불필요한 것 제거

#### 소스코드
- [x] Extension:LocalisationUpdate 설치(캐시 디렉토리 설정 등 포함)
- [x] crontab에 `extensions/LocalisationUpdate/update.php --quiet` 추가

**Comment by lens0021** [comment]
실행 시 `Found no new translations`만 반복되어 근본적 문제가 있는 것으로 보입니다. https://github.com/femiwiki/backupbot/issues/1 과도 관련이 있을 수 있어 비활성화합니다.

1. 도커 이미지 교체 없이 콘테이너 안에서 일시적으로 다음을 주석처리했습니다. https://github.com/femiwiki/mediawiki/blob/cc95e24bbe4c12143a2f72ab45df3015fdbad0fc/cron/localisation-update#L13
2. 코드에서도 수정했습니다. 다음 배포에 적용됩니다. &rarr; https://github.com/femiwiki/mediawiki/commit/2bd0b9eaaf1ebf18b7d4e42063ce38ed46206a65

**Comment by lens0021** [comment]
되는 거 같기도...? 한데 문제는 저희는 미디어위키 확장기능은 미디어위키 레포에서 받고 페미위키 확장기능은 확장기능에서 받아야 하는데 이런 설정은 LocalSettings.php에서는 안 되는 것 같고, 대신 크론잡으로 실행시킬 
 `php /path/to/your/wiki/extensions/LocalisationUpdate/update.php`에 `--repoid foo` 식으로 지정할 수 있는 것 같습니다. 대신 이러면 확장기능이 바뀔 때마다 크론텝을 고쳐야 하는 문제가 있는데 어차피 도커 이미지 매번 새로 구우니까 괜찮을 것 같기도 하고 그렇습니다...

**Comment by lens0021** [comment]
다른 문제가 생각났는데 L18n 캐시를 도커 콘테이너 밖으로 백업하지 않으면 콘테이너 껐다 켜면 다시 L18n 업데이트 하기 전까지는 최신 번역이 날아아겠네요 백업도 해야 겠습니다.

(EC2 인스턴스간에 백업까지는 안 해도 되지 않을까... 생각해봅니다)

**Comment by simnalamburt** [comment]
컨테이너 맨 처음 켤때에도 L18nUpdate가 무조건 한번 실행되도록 하기로함

캐싱은 안하고싶은데 업데이트속도가 너무 느려서 해야할듯

**Comment by lens0021** [comment]
현재 문제가 있는 부분: 개발 환경에서 콘테이너 안에서 `php extensions/LocalisationUpdate/update.php`하면 `/tmp/cache/l10nupdate-$language.json`가 생겨야 하는데 해봐도 생기지 않습니다!

(l10n_cache-$lang.cdb  파일들은 잘 생기는 걸로 봐서 서버에서 저 디렉토리에 쓰기 권한은 잘 갖고 있는 것 같습니다.)

추가: 성공한 경우에는 "Saved $count new translations"가 출력되어야 합니다

**Comment by lens0021** [comment]
안 되는 원인 찾았고 태스크([T237435](https://phabricator.wikimedia.org/T237435)) 팠고 코드 수정했고 리뷰 요청했습니다, 만은 이게 머지가 빠르게 되더라도 미디어위키 1.35에나 들어갈 거 같군요

**Comment by lens0021** [comment]
그 사이 조사해본 내용으로
- L18n 다운로드에는 Git 관련된 방법을 쓰고 있는 것이 아니라 GET Request를 사용하고 있어 github 토큰을 바로 어떻게 주기는 어려울 것 같습니다.
- 개발환경에서 `php update.php` 실행에 소요된 시간을 측정해볼려고 했는데 2시간 정도 돌렸는데도 ABC순으로 C에 해당하는 ConfirmEdit 확장기능을 업데이트 하고 있어 중단했습니다. 더 빠른 방법이 있으면 좋겠습니다.

<details>

> 컨테이너 맨 처음 켤때에도 L18nUpdate가 무조건 한번 실행되도록 하기로함
> 
> 캐싱은 안하고싶은데 업데이트속도가 너무 느려서 해야할듯

관련 디스코드 대화:

> simnalamburt: 저 플러그인 캐시 보존하게해여한다고하셔서<br>그러지마시고 걍 컨테이너 켜질때에 캐시업데이트를 무조건 하게만드는게<br>더 간단할거같아요
> lens0021: 좋아요<br>대신 이게 너무 오래걸려서 `php ... &` 같은 식으로 실행해야<br>될거에요
> simnalamburt: 아 느려요<br>느려요?<br>엄
> lens0021: 느리기도 느리고 제가 해보니까 몇번 하다가 깃헙에서 리밋걸던데<br>작동은 하는건가..
> simnalamburt: & 그거 잘못 돌리면 망해서
> lens0021: 한 세번 돌려서 그런가..
> simnalamburt: 깃헙에서 리밋거는건 API 토큰쓰면 리밋 풀리긴해요<br>퍼블릭 리포를 읽는데에 쓰는 토큰이니까<br>아무런 권한이 없는 깃헙 토큰 만들면<br>될거같네요
> lens0021: 그런 토큰을 추가하는 기능을 따로 못봤어요
> simnalamburt: ㅋㅋㅋㅋ<br>고쳐야겠네요
> lens0021: 환경변수?<br>읽나?<br>하튼 이건 별로 급한건아니고..
> simnalamburt: 느리면 걍 캐싱 해야겠당<br>ㅠㅠ

</details>

**Comment by lens0021** [comment]
API rate limit 관련, L18n Update를 git 리포에 대하여 사용하면 (코어 컴포넌트 수 + 모든 스킨 수 + 모든 확장기능 수) × 모든 언어 수(약 350개)번 GET request를 날린다는 것을 알 수 있었습니다. [wikimedia/puppet/blob/production/modules/scap/files/l10nupdate-1](https://github.com/wikimedia/puppet/blob/production/modules/scap/files/l10nupdate-1)을 참고하여 `git clone` 등으로 일단 json을 포함한 전체 리포들을 로컬에 받고 그 파일들을 이용해 업데이트하는 것으로 바꾸겠습니다. 더불어 가능하면 github 대신 [gerrit.wikimedia.org](gerrit.wikimedia.org)를 리모트로 이용하게 하겠습니다. 이를 위해 `femiwiki/base`에 git 이 필요합니다. (다만 쓰지도 않는 master 리포들을 로컬에 유지하기 때문에 용량이 낭비된다는 단점이 있습니다)

**Comment by lens0021** [comment]
실행 크론을 7일에 한 번으로 줄였는데요, 그 정도면 위키미디어 재단의 배포 주기인 일주일과 비교해도 괜찮을 것 같아서입니다(위키미디어는 LU를 안 쓰고 일주일마다 하는 배포로 대신하는 것 같습니다 세세한 정보는 [T220481](https://phabricator.wikimedia.org/T220481)과 그 관련된 긴 토론들을 확인해 주세요). 또 각종 명령에 `nice -n 19`를 추가했습니다.

**Comment by simnalamburt** [comment]
걍 API를 쏘는게 제일 깔끔하지 않을까요? 클론도 리포 커질수록 점점 느려질텐데..

**Comment by lens0021** [comment]
다음 문제가 있어서 [리버트](https://github.com/femiwiki/mediawiki/commit/dac2960524eed7cd6929c4187b54f353cdaed4d7)했습니다.

- `git clone`으로 extensions와 skins를 받을 때 사용하지 않는 것까지 클론됨
- `update.php`를 다른 `--repoid`에 대하여 복수 수행하면 덮어쓰기 되는 것 같음(확인 필요, 아마 아닐 것이긴 함)

다음 옵션 중에서 선택해야 할 것 같습니다.

- 리모트 리포들 전체를 `git clone` 혹은 tar.gz으로 받아서 LU 돌리기 - 안 쓰는 확장 기능 및 소스까지 받음 &rarr; :thinking:
- 사용하는 extensions/skins만 `git clone`으로 받아서 LU 돌리기 - 필요 없는 소스까지 받아짐 &rarr; :thinking:
- 사용하는 extensions/skins만 tar.gz으로 받아서 LU 돌리기 - 필요 없는 소스까지 받아짐 &rarr; :thinking:
- :heavy_check_mark:  LU가 JSON 파일을 하나 하나 받게 하기 
  - LU가 JSON 파일이 어떤 게 있는지를 API로 확인하고(속도 제한 있음) JSON 파일을 하나 하나 받는데(속도 제한은 없는 것 같음), 약 50*350=17500개의 JSON 파일을 받는 동안 매우 긴 시간이 걸립니다. &rarr; :thinking:
   - 토큰 없는 깃헙 API 호출은 한 시간 60회 제한인데,<sup>[[1]](https://developer.github.com/v3/#rate-limiting)</sup> 1회 호출 직후 350개의 json 파일을 받아서 확인하는 데에 1분 이상 걸릴 것 같아 리밋에 걸릴 가능성은 낮을 것 같습니다. 또 API 호출이 거의 하드코딩된 URL을 리퀘스트하는 것이라 토큰을 줄 여지가 현재는 없습니다.<sup>[[2]](https://github.com/femiwiki/mediawiki-extensions-LocalisationUpdate/blob/eb493b6/includes/fetcher/GitHubFetcher.php#L30)</sup>

:heavy_check_mark: 표시한 걸로 다시 할까요? LU가 급한 것도 아니니까 5시간이 걸리든 10시간이 걸리든 말든 상관 없을 것 같기도 하고..

**Comment by lens0021** [comment]
> `update.php`를 다른 `--repoid`에 대하여 복수 수행하면 덮어쓰기 되는 것 같음(확인 필요, 아마 아닐 것이긴 함)

실험해봤는데 그렇지는 않아 보입니다. 그러면 일주일에 한 번씩 JSON 다운로드 형식으로 돌리는 것으로 적용해보겠습니다.

**Comment by lens0021** [comment]
번역 메시지 다운로드에 부담이 어느 정도일지 몰라 손으로 한번 실행하고 괜찮으면 크론탭으로 옮기는 방식으로 단계적으로 적용하겠습니다.

**Comment by lens0021** [comment]
> 번역 메시지 다운로드에 부담이 어느 정도일지 몰라 손으로 한번 실행하고 괜찮으면 크론탭으로 옮기는 방식으로 단계적으로 적용하겠습니다.

대략 3시간 반 정도 걸렸는데요, CloudWatch에서 보기로는 크게 별 변화 없는 것 같습니다.
다만 문제는 `--repoid femiwiki`의 경우 잘못된 경로에 대한 API 호출을 너무 빠르게 많이 해서 속도 제한에 걸려 이내 실패합니다. 비활성화하기로 하고, 토큰을 쓸 수 있도록 [T238517](https://phabricator.wikimedia.org/T238517)을 만들었습니다.

<details>
<summary>관련 대화(2019.11.04.)</summary>
<dl>
<dt>simnalamburt</dt><dd>깃헙에서 리밋거는건 API 토큰쓰면 리밋 풀리긴해요
퍼블릭 리포를 읽는데에 쓰는 토큰이니까
아무런 권한이 없는 깃헙 토큰 만들면
될거같네요</dd>
<dt>lens0021</dt><dd>그런 토큰을 추가하는 기능을 따로 못봤어요</dd>
<dt>simnalamburt</dt><dd>ㅋㅋㅋㅋ
고쳐야겠네요</dd>
</dl>
</details>

**Comment by lens0021** [comment]
지금 콘테이너 안의 `/tmp/cache`에 있는 캐시들이 콘테이너 끄면 날아갈 관계로 다음 명령으로 콘테이너 밖 홈 폴더에 복사해놓습니다.

```sh
docker cp $(docker container ls -qf 'name=mediawiki_fastcgi'):/tmp/cache /home/ec2-user/i18n-cache
```

**Comment by lens0021** [comment]
배포하였으며 위에서 백업한 `/home/ec2-user/i18n-cache`는 다시 콘테이너 안으로 옮기고 삭제했습니다.
