### ISSUE TITLE
LocalSettings.php, secret.php 수정이 실시간으로 반영되도록 수정하기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#226]
이거 해결 안되면 배포 매우 힘들고 오토스케일 불가

### TODOs
- [x] 코딩 - https://github.com/femiwiki/mediawiki/pull/224
- [x] 리뷰 / 테스트
- [x] 배포 및 적용

### Activity
- Hyeon Kim added [this card](https://trello.com/c/BfO1Q64O) to 작업중 - Dec 23 at 12:32 AM
- Hyeon Kim joined this card - Dec 23 at 12:32 AM
- Hyeon Kim added 낙엽 to this card - Dec 23 at 12:32 AM
- 낙엽 Dec 23 at 1:43 AM <pre>[Run Command](https://ap-northeast-1.console.aws.amazon.com/ec2/home?region=ap-northeast-1#Commands:sort=CommandId) 혹시 쓸모 있나요?</pre>
- Hyeon Kim Dec 23 at 2:04 AM <pre>괜찮아보이네요</pre>
- Hyeon Kim Dec 23 at 2:34 AM <pre>@lens17 나중에 하면 좋을것같긴 한데 제가 사용법을 잘 모르겠고 저거 하려면 모든 인스턴스에 amazon-ssm-agent라는걸 깔아야하나보네요</pre>
- Hyeon Kim added TODOs to this card - Dec 23 at 4:40 AM
- Hyeon Kim completed 코딩 - https://github.com/femiwiki/mediawiki/pull/224 on this card - Dec 23 at 4:40 AM
- 낙엽 completed 리뷰 / 테스트 on this card - Dec 23 at 11:30 AM

**Comment by simnalamburt** [comment]
Closed by https://github.com/femiwiki/mediawiki/pull/224
