### ISSUE TITLE
페미위키 성능 최적화: 캐시

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#227]
https://www.mediawiki.org/wiki/Manual:Cache
https://www.mediawiki.org/wiki/Manual:Configuration_settings#Cache
https://www.mediawiki.org/wiki/Manual:Caching
https://www.mediawiki.org/wiki/Manual:Performance_tuning

```
$wgMainCacheType = CACHE_MEMCACHED;
$wgSessionCacheType = CACHE_MEMCACHED;
$wgMessageCacheType = CACHE_MEMCACHED;
$wgParserCacheType = CACHE_MEMCACHED;
```

어떻게 캐시를 구성하는게 제일 나을지 고민해보자 "SessionCache는 A memcached, 다른 캐시는 B memcached" 이런식의 설정이 불가능하여 어쩔 수 없이 하나의 memcached 프로세스를 여러 mediawiki 서버가 공유해야만 할 것 같다.

### TODOs
- [x] 코드 수정
- [x] #226 기다리기
- [x] 배포 및 테스트

### Activity
- Hyeon Kim added [this card](https://trello.com/c/w6YMXAc2) to 작업중 - Dec 21 at 1:05 AM
- 낙엽 moved this card from 작업중 to Backlog - Dec 21 at 8:40 PM
- Hyeon Kim moved this card from Backlog to 작업중 - Dec 22 at 11:42 PM
- Hyeon Kim joined this card - Dec 22 at 11:42 PM
- Hyeon Kim added TODOs to this card - Dec 23 at 12:15 AM
- Hyeon Kim completed 코드 수정 on this card - Dec 23 at 12:15 AM
- Hyeon Kim moved this card from 작업중 to 막힘/리뷰대기중 - Dec 23 at 12:31 AM

**Comment by lens0021** [comment]
Closed by 
https://github.com/femiwiki/mediawiki/commit/8fd0e5b0483fae197da553b4d7d4bb1897fc546b and https://github.com/femiwiki/database/commit/77efd3d9acfac3ecbd59f88d778cc6fd6c5057e4

**Comment by simnalamburt** [comment]
와와

**Comment by lens0021** [comment]
아니 이거 옛날건데..다시 이슈 열까요?

**Comment by simnalamburt** [comment]
카산드라까지 넣어서 해결 다 된거 아니에여?

**Comment by lens0021** [comment]
그럼 해결된걸로 합쉬다 도장꽝
