### ISSUE TITLE
이메일로 인한 비용 고민하기. 지금은 G Suite를 메일서버로 쓰고있음.

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#240]
다음 방안이 있음

1. 일반 지메일 계정 하나 + 메일건 프리티어
2. Zoho mail &rarr; https://github.com/femiwiki/femiwiki/issues/94

#### Activity
 - Hyeon Kim added [this card](https://trello.com/c/z8kjGDCk) to Backlog - Oct 7 at 12:46 AM

**Comment by HanbitGaram** [comment]
# 메일 골라보기
## Zoho
### 장점
- 조호는 다 좋습니다. 일단 다 장점같아요.
- 기존 페미위키 메일 모두 끌어다가 임포트 시킬 수 있어요.
- 메일 푸시알림 빠릿해요.

### 단점
- 모바일 앱이 iOS 기준으로 너무 안좋아요.
- Free가 5명 제한 있어요
- 용량 5기가에요. 언젠간 다 써버릴 것.
- 2FA QR돌려서 써야할 수 있어요. (차라리 돌려쓸거면 키베이스 암호화는 어떨까요)

## Mailgun + Gmail
### 장점
- 메일 포워딩이 자유로워요
- SMTP, IMAP 다 가능해요.
- API까지 줘요

### 단점
- 계정을 구글이랑 메일건 두개 만들어야해요
- 2FA QR을 공유해서 사용해야 할 수 있어요.
- API로 메일 보내는거 느려요. 90명에게 보내는데 2분 걸렸어요. (사용자)
- 10,000개 이상 쓰면 과금이에요.

**Comment by lens0021** [comment]
메일건과 SES 비교입니다.

|                   | [메일건 Concept plan]                           | [SES]                                                              |
| ----------------- | ----------------------------------------------- | ------------------------------------------------------------------ |
| Email             | 달에 10,000건 무료,<br/>이후 1,000건당 0.35 USD |
| EC2에서 보내기    |                                                 | 달에 62,000건 무료,<br/>이후 1,000건당 0.1 USD                     |
| EC2가 아닌 보내기 |                                                 | 1,000건당 0.1 USD                                                  |
| 받기              |                                                 | 달에 1,000건 무료,<br/>이후 1,000건당 0.1 USD                      |
| Validation        | 달에 100건 무료,<br/>이후 100건당 1 USD         |
| 비고              |                                                 | 발송 메일 데이터, 수신 메일 청크,<br/>EC2 데이터 송신 요금이 별도 부과 |

[메일건 concept plan]: https://www.mailgun.com/pricing/
[ses]: https://aws.amazon.com/ko/ses/pricing/

**Comment by simnalamburt** [comment]
Closed as duplicate of https://github.com/femiwiki/femiwiki/issues/72
