### ISSUE TITLE
마이너 가독성 개선

### ISSUE THREAD

**Issue by yeun** [femiwiki/docker-mediawiki#28]
- 맥으로 접속하면 시스템 기본 폰트가 보여지도록
  - 숫자와 영문은 UI에 최적화한 샌프란시스코가 보여지도록합니다. 단, 사용자가 일부러 OS기본 폰트를 바꾼 경우에는 사용자가 지정한 폰트가 보여지도록 합니다.
- 너무 작은 크기의 폰트 키우기
  - 12px, 13px의 폰트는 본문 대비 크기가 작아 잘 읽히지 않으며 링크일때는 누르기도 어렵습니다. 크기를 키워 개선합니다.
- 본문 폰트 크기 키우기
  - 본문 폰트 17px은 웹용 문서에 다소 작은 사이즈입니다. 크게는 23px까지도 쓰지만, 기존 유저의 괴리감을 고려해 19px로 키웁니다.
- 본문 글줄 너비 줄이기
   - 현재 한 글줄에 약 50자가 들어갑니다. 인쇄시 글줄을 생각해보면 두배 가까운 길이이며, 웹 환경을 고려해도 깁니다. 글줄 너비를 줄여 눈의 피로를 줄입니다.
- 줄간격 약간 줄이기
  - 현재 줄간격이 1.9em으로 꽤 높습니다. 적당한 줄간격은 쾌적함을 제공하지만 글자 크기의 두배에 가까워 문단이 묶이지 않는 문제가 있습니다. 이를 1.5-1.7em 정도로 줄입니다.
- 헤딩 텍스트 볼드로 변경
  - 헤드라인과 본문 모두 자족 400이 쓰여 문서에 강약이 부족합니다. 헤드라인을 700으로 설정해 리듬감을 만듭니다.

**Comment by tunarules** [comment]
좋은것 같습니다! 줄간격은 1.7em이 더 적당할것 같습니다. 저는 본문폰트를 23px까지 키우는것도 좋아요. 지금 폰트도 크다고 줄여서 보시는분들도 계시는....ㅠㅠ

**Comment by choidamdam** [comment]
페미위키 내에서 토론이 필요한 사항으로 보입니다.
https://femiwiki.com/w/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%EA%B0%9C%EC%84%A0%EC%9A%94%EC%B2%AD

**Comment by tunarules** [comment]
/Users/sollee1/Downloads/스크린샷 2017-08-07 오전 10.34.33.png

단어가 부서져 강제 줄바꿈 되는것을 단어 통째로 줄바꿈 시켜주는것으로 바꾸는것도 가독성에 더 좋을것 같습니다.

**Comment by yeun** [comment]
29일 주간회의에서 페미위키 내 토론하지 않아도 되는 사안이라고 논의했습니다.

**Comment by lens0021** [comment]
< dl>의 각 항목들 사이의 간격도 한 줄~한 줄반 정도로 띄우는 것이 어떨까요? 감사합니다!

**Comment by lens0021** [comment]
This issue was moved to femiwiki/skin#14
