### ISSUE TITLE
InstantCommons 사용이 느림

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#284]
https://femiwiki.com/w/%EC%A3%BC%EC%A0%9C:Uifvczbgn9hz94if

[InstantCommons](https://www.mediawiki.org/wiki/InstantCommons) 라는 미디어위키 기능을 활용해 문서에 Wikimedia Commons의 사진을 사용한 경우, 사진의 수에 비례해 서버의 응답 시간이 느려진다. 사진이 15개 이상일 경우 거의 3분 정도 걸림

(마치 서버에서 캐시가 되는 것처럼)일단 한 번 연 이후에는 모든 사람에게 빠르게 열리나 얼마가 지난 후에는 다시 느려짐

**Comment by simnalamburt** [comment]
https://phabricator.wikimedia.org/T190576 이 버그인듯합니다.

**Comment by simnalamburt** [comment]
파서가 실행되면서 이미지 태그를 만날때마다 이미지 썸네일 URL을 알아내느라 HTTP 요청을 동기적으로 하나하나 호출하는게 문제였음. 아래는 스택트레이스


- curl_init() https://github.com/wikimedia/mediawiki/blob/1.33.1/includes/http/CurlHttpRequest.php#L93
- execute() https://github.com/wikimedia/mediawiki/blob/1.33.1/includes/filerepo/ForeignAPIRepo.php#L528
- httpGet() https://github.com/wikimedia/mediawiki/blob/1.33.1/includes/filerepo/ForeignAPIRepo.php#L572
- {closure}() https://github.com/wikimedia/mediawiki/blob/1.33.1/includes/filerepo/ForeignAPIRepo.php#L572
- {closure}() https://github.com/wikimedia/mediawiki/blob/1.33.1/includes/libs/objectcache/WANObjectCache.php#L1253
- doGetWithSetCallback() https://github.com/wikimedia/mediawiki/blob/1.33.1/includes/libs/objectcache/WANObjectCache.php#L1414
- getWithSetCallback() https://github.com/wikimedia/mediawiki/blob/1.33.1/includes/libs/objectcache/WANObjectCache.php#L1235
- httpGetCached() https://github.com/wikimedia/mediawiki/blob/1.33.1/includes/filerepo/ForeignAPIRepo.php#L568
- fetchImageQuery() https://github.com/wikimedia/mediawiki/blob/1.33.1/includes/filerepo/ForeignAPIRepo.php#L203
- getThumbUrl() https://github.com/wikimedia/mediawiki/blob/1.33.1/includes/filerepo/ForeignAPIRepo.php#L266
- getThumbUrlFromCache() https://github.com/wikimedia/mediawiki/blob/1.33.1/includes/filerepo/ForeignAPIRepo.php#L359
- transform() https://github.com/wikimedia/mediawiki/blob/1.33.1/includes/filerepo/file/ForeignAPIFile.php#L132
- processResponsiveImages() https://github.com/wikimedia/mediawiki/blob/1.33.1/includes/Linker.php#L656-L657
- makeImageLink() https://github.com/wikimedia/mediawiki/blob/1.33.1/includes/Linker.php#L426
- makeImage() https://github.com/wikimedia/mediawiki/blob/1.33.1/includes/parser/Parser.php#L5462
- replaceInternalLinks2() https://github.com/wikimedia/mediawiki/blob/1.33.1/includes/parser/Parser.php#L2422
- replaceInternalLinks() https://github.com/wikimedia/mediawiki/blob/1.33.1/includes/parser/Parser.php#L2173
- internalParse() https://github.com/wikimedia/mediawiki/blob/1.33.1/includes/parser/Parser.php#L1384

**Comment by lens0021** [comment]
https://phabricator.wikimedia.org/T56037 is still open.

**Comment by lens0021** [comment]
https://lists.wikimedia.org/hyperkitty/list/mediawiki-l@lists.wikimedia.org/thread/QUSUGOYBTG2WQD63MOX3FGT6Y44VLUZB/

>I'd like to announce my new extension QuickInstantCommons [1]. Basically it
is a version of InstantCommons, except fast.
>
>I used [[List_of_governors_general_of_Canada]] as a test page (85 images)
with caching disabled. Initial results were very promising:
>* Vanilla MediaWiki: 1038.2 seconds (17 minutes)
>* This extension (when it isn't able to prefetch): 18.5 seconds (56 times
as fast)
>* This extension (when it is able to prefetch): 1.1 seconds (943 times as
fast)
>
>Also it supports thumbnailing files even if you're missing the media
handler extension for the format in question (but only in a limited way).
So for example, you can still see SLA files, even if you don't have
Extension:3D installed (but the interactive features don't work).
>
>It does a bunch of things to speed things up - but the primary things are:
>* Use HTTP/2
>* Avoid unnecessary HTTP requests
>* Attempt to guess what images will be used on the page based on the
previous version of the page, and prefetch those images.
>
>If you're currently using InstantCommons/ForeignAPIRepo, consider trying
>the new extension out and let me know what you think!
>
>[1] https://www.mediawiki.org/wiki/Extension:QuickInstantCommons
