### ISSUE TITLE
레이블 개선

### ISSUE THREAD

**Issue by yeun** [femiwiki/docker-mediawiki#29]
- "편집" 과 "원본 편집"
  - 이 둘을 눌러보기 전에는 어떤 차이가 있는지 알기 어렵습니다. 둘의 차이를 직관적으로 표현하는 레이블이 필요합니다.
- "주시"와 "주시 해제", "주시 문서 목록"
   - 익숙하지 않은 한자어인 "주시"보다는 "관심" 같이 UI에 익숙한 레이블이 좋을 것 같습니다. 
- "행위"와 "도구"
   - 행위는 Action의, 도구는 tool의 번역어로 보입니다. 둘 다 한국어로 번역하면 카테고리 상의 차이를 이해하기 어려워 좀더 분명한 레이블이 필요합니다. 이 부분은 타이틀이 아예 없이 UX적으로 기능 구성을 수정하는게 좋아보이기도 합니다.
- "보호", "보호 확인", "보호 설정" 등
   - 레이블로써 익숙하지 않은 단어라 무엇을 뜻하는지 알기 어렵습니다. 직관적으로 이해할 수 있는 레이블로 수정합니다.
- 문서의 편집이나 보호 모드로 들어갔을때 나오는 "보기"
   - 다시 문서로 돌아가는 기능으로 추정합니다. 그렇다면 "문서로 되돌아가기" 혹은 "문서 보기" 등으로 수정하면 좋겠습니다. 레이블의 위치도 좌측 상단으로 옮기면 좋겠습니다.
- 빈 문서에 나오는 "생성"과 "만들기"
   - 한 페이지 내에 같은 의미로 다른 단어가 쓰이고 있습니다. 하나로 통일합니다.
- "인쇄용 판"
   - 번역투의 레이블입니다. 순화하면 좋겠습니다.
- "다면 분류 목록"
   - 레이블만 봐서는 어떤 의미인지 알기 어렵습니다. 
- "보여줄 제목"
   - 보여줄 제목 외에 숨겨진 제목 등 다른 용도의 제목이 없다면 그냥 "제목"이라고 표시하는게 좋을 것 같습니다.
- "가리키는 글의 바뀜"
   - 전반적으로 "글"의 의미로 "문서"를 사용하고 있고 "바뀜"이 마치 바꾸는 행위를 지칭하는 듯해서 "가리키는 문서 변경 이력" 등으로 수정하면 좋을 것 같습니다.

**Comment by choidamdam** [comment]
기술적인 부분이 아니라서 페미위키 내에서 토론이 필요한 사항으로 보입니다.
https://femiwiki.com/w/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%EA%B0%9C%EC%84%A0%EC%9A%94%EC%B2%AD

**Comment by lens0021** [comment]
저도 적습니다.
- "최근 바뀜"과 "바뀐글"
  - 페미위키 자체에서는 전반적으로 바뀐글이라는 용어를 쓰는 것 같은데 미디어위키의 기본 명칭이 최근 바뀜이라 섞인 것 같습니다. 바뀐글로 통일하면 좋겠습니다.
- 시각편집기의 "점 목록/숫자 목록"과 원본편집기의 "글머리 기호 목록/번호가 매겨진 목록"
- "계정"과 "사용자"
  - 같은 개념을 "계정 만들기" 등에서는 "계정"으로, "사용자 권한"이나 "사용자 목록" 등에서는 사용자로 표기 중입니다. 구분을 확실하게 짓고 정리하면 좋겠습니다.

**Comment by lens0021** [comment]
This issue was moved to femiwiki/skin#13
