### ISSUE TITLE
사용자 비밀번호 정책 만들기

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/docker-mediawiki#299]
NIST 가이드라인이 제일 안전하고 유저에게도 편합니다. https://en.wikipedia.org/wiki/Password_policy#NIST_guidelines

**Comment by lens0021** [comment]
[`$wgPasswordPolicy`](https://www.mediawiki.org/wiki/Manual:$wgPasswordPolicy)으로 설정할 수 있다고 합니다~

**Comment by lens0021** [comment]
정정합니다 $wgPasswordPolicy으로 NIST 가이드라인중에 할 수 있는 건 거의 글자수 제한밖에 없는듯 합니다~

**Comment by lens0021** [comment]
지금 미디어위키 기본값이 아래와 같은데요

- MinimalPasswordLength: 8
- PasswordCannotBeSubstringInUsername: true
    ```php
    $username = $user->getName();
    if ( $policyVal && stripos( $username, $password ) !== false ) {
    	$status->error( 'password-substring-username-match' );
    }
    ```
- PasswordCannotMatchDefaults: true (`Check if username and password are on a list of past MediaWiki default passwords.`)
- PasswordNotInCommonList: true ([List of the 100,000 most commonly used passwords](https://packagist.org/packages/wikimedia/common-passwords))

일단 이 정도로 만족해도 될 것 같아서 닫습니다.
