### ISSUE TITLE
hover시 생기는 밑줄과 글자 사이 간격 벌림

### ISSUE THREAD

**Issue by yeun** [femiwiki/docker-mediawiki#30]
현재는 링크에 마우스를 올렸을 때 밑줄이 바로 글자 밑에 생겨 가독성을 해칩니다.
<img width="176" alt="screen shot 2017-08-04 at 10 24 57 pm" src="https://user-images.githubusercontent.com/6580407/28970646-453c6d68-7964-11e7-9118-be2faebcb3d5.png">

이 간격을 약간 떨어트려 읽기 쉽게 합니다.
<img width="145" alt="screen shot 2017-08-04 at 10 27 20 pm" src="https://user-images.githubusercontent.com/6580407/28970660-5024bcc6-7964-11e7-9fdf-540512b4faf4.png">

**Comment by yeun** [comment]
<img width="300" alt="screen shot 2017-08-05 at 12 14 45 am" src="https://user-images.githubusercontent.com/6580407/28974923-21988252-7973-11e7-999f-3b5422845e35.png">

작업했는데 위와 같은 상황이 생겨 #31 을 만들었습니다.

**Comment by lens0021** [comment]
This issue was moved to femiwiki/skin#15

**Comment by lens0021** [comment]
@yeun 님 혹시 이슈 본문에 스크린샷 <img width="145" alt="screen shot 2017-08-04 at 10 27 20 pm" src="https://user-images.githubusercontent.com/6580407/28970660-5024bcc6-7964-11e7-9fdf-540512b4faf4.png"> 이것이 어떻게 하신 건지 알려주실 수 있나요??
