### ISSUE TITLE
편집 도움말 패널 활성화하기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#306]
편집 도움말 패널은 한국어 위키 백과에서 편집을 하려 할 때 다음과 같이 화면 오른쪽 아래 나오는 풍선 모양 아이콘입니다.

![image](https://user-images.githubusercontent.com/28209361/68132174-96e4d300-ff61-11e9-913c-145d7863d76e.png)
![image](https://user-images.githubusercontent.com/28209361/68132186-9c421d80-ff61-11e9-9c2e-c68329f0ed50.png)

**Comment by lens0021** [comment]
위키백과에 있어서 쉽게 도입할 수 있을줄 알았는데, 조사해보니 이 기능이 아직 한참 개발 중인 기능이라 확장기능도 [GrowthExperiments](https://www.mediawiki.org/wiki/Extension:GrowthExperiments)이라는 확장기능 안에 셋방살이를 하고 있다는 걸 알았습니다. (Growth 팀은 위키미디어 재단의 팀 이름 중 하나이고 저 확장기능은 해당 팀이 종합적으로 쓰는 리포지토리로 보입니다)

한국어 위키백과는 따로 신청을 해서 지금 알파?처럼 참여하고 있는 것으로 보이고, 여하간 페미위키에서 바로 쓸 수는 없을거 같습니다 :sweat:

**Comment by revi** [comment]
> 한국어 위키백과는 따로 신청을 해서 지금 알파?처럼 참여하고 있는 것으로 보이고, 여하간 페미위키에서 바로 쓸 수는 없을거 같습니다 😓

신청은 아니구요 Growth Team 알파 테스트 위키가 한국어 위키백과라 Growth 팀의 모든 신기능은 한구거 / 체코어 / 아랍어 / 베트남어 위백에 무조건 선배포됩니다. 나머지는 베타 옵트인.

**Comment by lens0021** [comment]
Closed by https://github.com/femiwiki/docker-mediawiki/pull/543
