### ISSUE TITLE
GrowthExperiments 디플로이

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#307]
![image](https://user-images.githubusercontent.com/28209361/68296776-b6ead280-00d8-11ea-8f49-ee72bd5d8b5e.png)

- [x] https://femiwiki.com/w/MediaWiki:growthexperiments-tour-discovery-title 수정
- [x] https://femiwiki.com/w/MediaWiki:growthexperiments-tour-discovery-description 수정

[Newcomer homepage](https://www.mediawiki.org/wiki/Special:MyLanguage/Growth/Personalized_first_day/Newcomer_homepage)는 위키미디어 재단에서 한창 개발 중인, 방금 막 위키에 가입한 사람을 위한 특수한 페이지입니다.

~~아직 개발중이라 쓰지는 못하지만 우선 Newcomer homepage의 의존성들을 준비하면 좋겠습니다.~~

[Update] 2019년 12월부터 Stable으로 표시되었습니다.[1]

1: https://www.mediawiki.org/w/index.php?title=Extension:GrowthExperiments&oldid=3569087

**Comment by simnalamburt** [comment]
오 뭔가 신기하네요
