### ISSUE TITLE
tag에 들어간 스타일 제거하고 적절한 클래스 삽입

### ISSUE THREAD

**Issue by yeun** [femiwiki/docker-mediawiki#31]
현재 div, a, input 등 태그에 스타일이 지정되어있어서 스타일을 수정하면 예기치않은 사이드 이펙트가 발생합니다. 각 영역에 적절한 클래스를 만들어 유지보수가 쉽도록 스타일을 분산합니다.

**Comment by lens0021** [comment]
This issue was moved to femiwiki/skin#20
