### ISSUE TITLE
Organization 설명 업데이트하기

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/docker-mediawiki#32]
@minortriad @choidamdam 어드민 권한이 없어서 저는 할 수 없군요.. 업데이트 부탁드립니다~

### TODOs
- [x] 설명 업데이트
- [x] 프로필사진 업데이트
- [x] 디스코드-깃헙 봇 연동
- [x] @vvvvviral 님 멤버로 추가

<img width=400 src=https://cdn.discordapp.com/attachments/341920917556953089/343035405479706625/2017-08-04_11.20.06.png>

![logo](https://user-images.githubusercontent.com/4435445/28974547-b6b84f5e-7971-11e7-98f5-5647c7330b68.png)

**[로고 다운로드](https://user-images.githubusercontent.com/4435445/28974547-b6b84f5e-7971-11e7-98f5-5647c7330b68.png)**

**Comment by minortriad** [comment]
done.
