### ISSUE TITLE
아이디와 별도의 닉네임 지원

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#34]
현재는 닉네임을 따로 지원하지 않고, 대신 한글 아이디가 설정이 가능하지만 처음 가입할 때는 이를 알기가 어려워 많은 사용자가 가입 직후 아이디를 변경하고 있습니다.

만일 아이디와 별도로 제공되는 닉네임 기능이 있다면 이 문제가 개선될 것으로 예상합니다.

위키에선 https://femiwiki.com/w/%EC%A3%BC%EC%A0%9C:Tsdf8zs84l2ro2l3 에서 이야기 나눈 적 있습니다.

**Comment by choidamdam** [comment]
꽤 중요한 변경 사항으로 보이는데 다음 사항에 대해 고려할 점이 있을 것 같습니다.

- 가입 화면에서 한글 사용자명 지원 여부 및 ID와 사용자명이 동일하다는 것을 미리 고지하는 더 단순한 대안
- 이 변경에 대해 공론화 및 총의가 충분히 형성되었는지
- Realname 확장의 변경점이 명확하지 않으므로 별도의 저장소를 추가할 필요

**Comment by lens0021** [comment]
@choidamdam 앞의 둘은 이해가 가는데 세번째인 별도의 저장소를 추가할 필요라는 건 어떤 뜻인가요?

**Comment by choidamdam** [comment]
@lens0021 업스트림과의 변경점을 추적할 수 없으므로, 저장소를 fork 후 관리하는 게 좋을 것 같다는 의미입니다.

**Comment by lens0021** [comment]
@choidamdam 죄송합니다, 제가 관련 지식이나 경험이 없어서 말씀하시는 바를 잘 이해하지 못 하였습니다. 더 쉽게 풀어 설명해 주셔도 제가 이해할 자신이 없습니다. 모쪼록 답변 주셔서 감사합니다.

그러면 거듭 죄송합니다, 다시, Realname 확장과 관련하여 제가 따로 할 수 있는 일이 없는지를 여쭤볼 수 있을까요?

**Comment by choidamdam** [comment]
@lens0021 일단 공론화가 선진행되는 것이 우선일 것 같습니다.

마지막 건은, Realname 확장을 수정하여 포함하는 것이기 때문에 바로 커밋을 하면 원본 소스에서 변경된 항목을 확인하기 힘들다는 내용입니다. 그리고 업스트림에 수정 사항이 생기면 추후 반영하는 등 관리 소요가 생기므로 Realname 확장을 포함하고 싶다면 Realname 원 소스(저장소)를 fork한 별도 저장소를 생성하여 관리하는 것이 좋을 것 같습니다.

**Comment by lens0021** [comment]
페미위키에서 [설문](https://goo.gl/QTuiAP)을 시작하고, [저장소를 생성](https://github.com/lens0021/mediawiki-extensions-Realnames)하였습니다. 설문 결과가 긍정적이면 더 진행해 보겠습니다.

**Comment by lens0021** [comment]
설문 응답수가 적긴 하지만 현재 응답한 일곱 분 중 여섯 분이 찬성하였으며, #72 에서는 다섯 분이 우려된다고 응답하신 '변경 이력이 표시되지 않는점'을 수정하여 '닉네임 변경 기록'이 남도록 하였습니다.
> 9월 11일 업데이트: 응답자 아홉분 중 일곱분이 찬성 상태입니다.
