### ISSUE TITLE
AbuseFilter 확장기능 설치

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#35]
편집 필터를 설정할 수 있는 [AbuseFilter 확장기능](https://www.mediawiki.org/wiki/Extension:AbuseFilter)의 설치가 위키 커뮤니티에서 요청되었습니다.

위키의 게시물 주소는 https://femiwiki.com/w/%EC%A3%BC%EC%A0%9C:Trkigjj5i8wc7yfr 입니다.

**Comment by choidamdam** [comment]
2017/8/8 배포 완료했습니다.
