### ISSUE TITLE
게시판 이름공간을 콘텐츠 이름공간이 아니도록 설정하기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#36]
콘텐츠 이름공간은 위키의 콘텐츠인지 아닌지를 설정하는 옵션으로, 현재 "게시판", "자유게시판", "가입인사게시판"이 모두 콘텐츠 이름공간으로 설정되어 있으며 이에 따라 [[특수:임의문서]], [[특수:짧은문서]] 등 특수문서들이 각 문서의 설계의도와 어긋나게 게시판 게시물들을 표시하고 있습니다.

콘텐츠 이름공간이 아니도록 설정할 필요가 있어 보입니다.

**Comment by choidamdam** [comment]
2017/8/8 배포 완료했습니다.
