### ISSUE TITLE
문서가 간접적으로 속한 모든 분류를 보여주는 기능 추가하기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#37]
분류가 다음과 같이 되어 있다고 가정할 때, 각각을 차례로 A, B, C라고 이름 붙이면
- 종류/탈것 ⊃ 종류/자동차 ∋ 종류/스포츠카

A→B, A→C, B→A, B→C, C→B 링크는 각 문서에 바로 존재하지만 C→A는 존재하지 않습니다.

구체적으로 예를 들면 페미위키 문서의 경우 CB링크는 "성격/여성주의 위키", "언어/한국어", "상태/운영중"이며, CA링크는 "성격/여성주의 위키", **"주제/페미니즘"**, **"성격/페미니즘"**, **"성격/위키"**, **"성격/웹사이트"**, **"매체/인터넷"**, "언어/한국어", "상태/운영중"입니다(둘의 차이는 강조표시했습니다).

보시다시피 CA 링크를 모두 보여주는 것은 CB 링크만 보여주는 것에 비해 직관적이지 않아 기본적으로 모두 표시되게 하기에는 어려운 점이 있습니다. 그러므로 기본으로는 CB 링크만을 보여주되 펼치기나 더보기와 같은 느낌이 드는 버튼을 누르면 CA 링크가 추가로 표시되도록 하면 좋겠습니다.

**Comment by choidamdam** [comment]
2017/8/8 배포 완료했습니다.
