### ISSUE TITLE
Mathjax 클래스로 표시된 수학식의 스타일 구분

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#38]
[온라인 도움말](https://www.sharelatex.com/learn/Display_style_in_math_mode)을 보면 Tex에서 수학식을 입력할 때 \displaystyle라는 명령어로 수학식을 좀 더 돋보이게 하는 기능이 있었던 것 같습니다.

근데 그 기능이 MathJax와 simpleMathjax확장기능을 거쳐 위키로 넘어오면서 어느샌가 사라진 것 같습니다. 막 사라진 건 아니고 [설명서](https://www.mediawiki.org/wiki/Extension:SimpleMathJax)로 추측하건데 displaystyle이 기본값이 되고 입력을 다르게 하면 inlineMath라는 이름으로 displaystyle이 아니게 처리하게 된 것 같습니다.

그리고 수학식을 다루는 거의 모든 미디어위키 엔진 위키는 그냥 이런 기능은 사용하지 않고 그냥 사용자가 알아서 적당히 줄을 바꾸고 왼쪽에 여백을 주는 것으로 편집 관습이 굳어진 것 같습니다.

이 부분을

1. displaystyle으로 보이려고 한 것 같은 Mathjax만 적당히 감지하여 처리하기
2. 혹은 inlineMath 문법을 지원하기

두 가지 중 하나를 하면 좋겠습니다. 일단 현재 페미위키에 수학 문서에 가장 많이 기여하시는 분에게만 말씀 드려서 원하는 대로 수정을 해봐도 괜찮다는 허락을 구했습니다.(https://femiwiki.com/w/%EC%A3%BC%EC%A0%9C:Tuela11rmnt9de6v) 

그래도 개인적으로는 2번보다 1번이 수학식 입력 문법에 변하는 점이 적고 기존 문법과도 호환이 되어서 1번으로 진행하고 있었습니다.

하여튼 개선이 되면 좋겠습니다.

**Comment by choidamdam** [comment]
2017/8/8 배포 완료했습니다.
