### ISSUE TITLE
사이트 메뉴의 알림과 메시지 팝업 표시 버그

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#39]
direction이 rtl로 설정되어 배치가 깨지고 스크롤바가 왼쪽에 표시되고 있습니다.

제가 #23 에서 만든 버그이며 세부 항목을 ltr로 설정해야 겠습니다.

**Comment by choidamdam** [comment]
2017/8/8 배포 완료했습니다.
