### ISSUE TITLE
구글 크롬 모바일 웹 앱 개선

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#41]
- 이름이 "App"이라고 되어 있는데 페미위키를 나타내는 이름으로 변경하면 좋겠습니다. 
- 웹앱에 색 설정이 가능한데 페미위키의 색을 설정하면 좋겠습니다.
- 웹앱을 보통 전체화면을 많이 쓰니 페미위키 웹 앱도 전체화면으로 변경하면 좋겠습니다.

**Comment by choidamdam** [comment]
2017/8/8 배포 완료했습니다.
