### ISSUE TITLE
열고 닫는 목적의 토글 버튼들의 통일

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#43]
- 사이트 메뉴: 오른쪽, 三자 고유 버튼
- 일반 문서 메뉴: 오른쪽 ••• 버튼
- 최근 바뀜의 토글 버튼: 왼쪽, 회색 세모
- 토론문서의 각 게시물 메뉴: 오른쪽 ••• 버튼
- 분류 트리의 토글 버튼: 왼쪽, 파란 색 세모
- 문서에서 사용되는 글 펼치기 숨기기 버튼: 오른쪽,  텍스트

자리를 우선으로 하여 오른쪽으로 옮기고, 모양을 두 번째 우선으로 하여 가능한 만큼만 통일하면 좋겠습니다.

**Comment by choidamdam** [comment]
관련하여 페미위키 상 논의가 필요할 것 같습니다.

**Comment by lens0021** [comment]
This issue was moved to femiwiki/skin#17
