### ISSUE TITLE
Use composer 2.0

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/docker-mediawiki#466]
It's much faster!

##### References
- https://blog.packagist.com/composer-2-0-is-now-available/
- https://github.com/wikimedia/composer-merge-plugin/pull/189

**Comment by lens0021** [comment]
https://github.com/wikimedia/composer-merge-plugin/issues/184 is resolved

**Comment by lens0021** [comment]
MW 1.35.2 나오면 그때 가능할 것 같습니다

```
Your requirements could not be resolved to an installable set of packages.
 
   Problem 1
     - Root composer.json requires composer-plugin-api ^1.1, found composer-plugin-api[2.0.0] but it does not match the constraint.
   Problem 2
     - Root composer.json requires wikimedia/composer-merge-plugin 1.4.1 -> satisfiable by wikimedia/composer-merge-plugin[v1.4.1].
     - wikimedia/composer-merge-plugin v1.4.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
```

**Comment by lens0021** [comment]
Unblocked as MW 1.35.2 has been released. https://lists.wikimedia.org/pipermail/mediawiki-announce/2021-April/000272.html

**Comment by lens0021** [comment]
Closed by https://github.com/femiwiki/docker-mediawiki/commit/279a8739e86fddccba7d1ce74468b23fd3a867fb
