### ISSUE TITLE
Increase max fd number of caddy

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/docker-mediawiki#467]
https://github.com/femiwiki/docker-mediawiki/blob/d3ba6b416f157fccf8d257f704faf0ab9b6909be/production.yml#L9-L12

도커 컴포즈 파일에 ulimits을 지정하긴 했지만, 도커 20.10.0 이전버전에선 스웜모드에서 쓸 수 없다.

##### Reference
- https://github.com/moby/moby/pull/41284
- https://github.com/docker/cli/pull/2712

**Comment by lens0021** [comment]
Added in the nomad job file https://github.com/femiwiki/nomad/blob/0ea959c857db8a1b97f3afd34310465e3c5c88f5/jobs/http.nomad#L23

**Comment by lens0021** [comment]
We have completely migrated to Nomad.
