### ISSUE TITLE
화면 폭이 400px 미만일 때 PopupWidget 일부가 정상적으로 표시되지 않는 문제

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#57]
화면 폭이 400px 미만일 때 [PopupWidget](https://www.mediawiki.org/wiki/OOjs_UI/Widgets/Popups)(div.oo-ui-popupWidget-popup) 중 일부가 다음과 같이 표시되어 사용할 수 없습니다.

![image](https://user-images.githubusercontent.com/28209361/28992755-f889aa5e-79df-11e7-9d8a-353dda6aa9a0.png)

다음은 구체적인 예입니다.
- 시각편집기의 링크 추가 팝업

다음은 해당하지 않는 예입니다.
 - Flow 시각편집기의 언급(멘션) 추가 팝업

**Comment by choidamdam** [comment]
2017/8/8 배포 완료했습니다.
