### ISSUE TITLE
화면 폭이 좁을 때 Menu Layout이 정상적으로 이용하기 힘든 문제

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#58]
시각편집기 등의 [Menu Layout](https://www.mediawiki.org/wiki/OOjs_UI/Layouts/Menu_Layout)이 화면 폭이 좁은 환경에서는 다음과 같이 표시되어 이용이 매우 어렵습니다.
![image](https://user-images.githubusercontent.com/28209361/28992792-068cc20c-79e1-11e7-82b0-69f5fdd5bcd4.png)

폭이 좁은 경우에 한하여 다음과 같이 표시되면 좋겠습니다.
![image](https://user-images.githubusercontent.com/28209361/28992813-7e873508-79e1-11e7-98db-cd78be654856.png)

**Comment by choidamdam** [comment]
2017/8/8 배포 완료했습니다.
