### ISSUE TITLE
상단바 UX 리뉴얼

### ISSUE THREAD

**Issue by tunarules** [femiwiki/docker-mediawiki#61]
1. 검색창의 위아래 간격이 애매함.
2. 로고에 맞춰 아이콘 개선.

**Comment by lens0021** [comment]
id가 p-logo인 h1에 border-bottom이 설정되어 있어서 다음과 같이 확대해서 보편 페미위키 로고 아래 회색 줄이 있는데 이것도 같이 없애면 좋겠습니다.
![image](https://user-images.githubusercontent.com/28209361/28996302-8a1ec596-7a38-11e7-8511-166a7c33e807.png)

**Comment by lens0021** [comment]
This issue was moved to femiwiki/skin#12
