### ISSUE TITLE
최근편집/원본보기 부분 수정

### ISSUE THREAD

**Issue by melonnnn** [femiwiki/docker-mediawiki#62]
# 최근편집
_- 최신/이전 부분 가독성 떨어짐 : 들여쓰기 필요, 줄 길이 줄이면 좋겠다._
------------------------------------------------------------------------------------
<img width="842" alt="2017-08-05 5 45 05" src="https://user-images.githubusercontent.com/30746622/28994305-0009ec14-7a06-11e7-9a97-280611a4edc7.png">

# 원본보기
_- 윗부분(안내문구) 그레이 처리&글씨크기 작게하면 좋겠다._ 
------------------------------------------------------------------------------------
<img width="864" alt="2017-08-05 5 46 02" src="https://user-images.githubusercontent.com/30746622/28994306-000be19a-7a06-11e7-85e5-3a96a7e30f3a.png">

**Comment by lens0021** [comment]
I referenced this issue

[**주제:Trkidraq5p6r2wwn**](https://femiwiki.com/w/%EC%A3%BC%EC%A0%9C:Trkidraq5p6r2wwn)

**Comment by lens0021** [comment]
This issue was moved to femiwiki/skin#11
