### ISSUE TITLE
문서 읽기화면의 목차 단계 가독성 개선

### ISSUE THREAD

**Issue by vvvvviral** [femiwiki/docker-mediawiki#63]
* 문서의 목차 단계가 많아질수록 본문과 비슷해짐
* 목차 내용임을 구별할 수 있는 것이 문단 구분이나 앞머리의 줄번호밖에 없음

**Comment by vvvvviral** [comment]
목차를 누르면 문서 최상단 혹은 목차 위치로 이동하도록 하면 좋겠다는 의견이 있습니다.

**Comment by lens0021** [comment]
This issue was moved to femiwiki/skin#10
