### ISSUE TITLE
MediaWiki 1.31.x 업그레이드

### ISSUE THREAD

**Issue by choidamdam** [femiwiki/docker-mediawiki#67]
현행 사용 중인 MediaWiki 1.27.1에서 최신 안정 버전인 1.29.x로 업그레이드

**Comment by lens0021** [comment]
1.29에서 틀 이름공간의 하위문서 허용이 기본값이 되었다고 합니다([릴리즈 노트](https://www.mediawiki.org/wiki/Release_notes/1.29#Configuration_changes_in_1.29)), 그래서 맞다면 업그레이드 시 다음을 지워도 될 것 같습니다.
https://github.com/femiwiki/femiwiki.com/blob/9c40008be56a70891276a7f4fdd4afdb912dd8e2/www/LocalSettings.php#L155-L156

**Comment by lens0021** [comment]
2018년 5월 기준 1.30이 안정 버전이라 수정합니다.

**Comment by lens0021** [comment]
2018년 9월 24일 적용

**Comment by simnalamburt** [comment]
낙엽님께서 쓰신 미디어위키 1.31 업그레이드 사전 보고서 링크

https://docs.google.com/document/d/1ebN902sPkGNP329JGxSLASgGw5yrlRwqE94QfcG-vUM

**Comment by lens0021** [comment]
점검 시나리오 등은 https://github.com/femiwiki/femiwiki/issues/21 참고, 사전보고서는 https://femiwiki.com/w/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%EA%B0%9C%EB%B0%9C_%EB%B8%94%EB%A1%9C%EA%B7%B8/6 으로도 복제함
