### ISSUE TITLE
위키 콘텐츠와 관련된 CSS는 서버 대신 미디어위키:common.css로 옮기기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#77]
([주제:Tufi4iiuqv84nd3r](https://femiwiki.com/w/%EC%A3%BC%EC%A0%9C:Tufi4iiuqv84nd3r)에서 이동)

예를 들면 [틀:알림 상자](https://femiwiki.com/w/%ED%8B%80:%EC%95%8C%EB%A6%BC_%EC%83%81%EC%9E%90)를 위한 .notice나 [틀:달력](https://femiwiki.com/w/%ED%8B%80:%EB%8B%AC%EB%A0%A5)을 위한 .fw-calendar 같은 것을 말인데요, 전자는 [www/skins/Femiwiki/resources/screen-common.less](https://github.com/femiwiki/femiwiki.com/blob/master/www/skins/Femiwiki/resources/screen-common.less)에, 후자는 [screen-table.less](https://github.com/femiwiki/femiwiki.com/blob/master/www/skins/Femiwiki/resources/screen-table.less)에 정의되어 있습니다.

페미위키 콘텐츠와 관련된 것인데도 수정을 하려면 서버를 건드려야 한다는 점이 좋지 못한 것 같습니다, 그래서 페미위키 내 관리자 권한만 있어도 수정이 가능한 [미디어위키:common.css](https://femiwiki.com/w/%EB%AF%B8%EB%94%94%EC%96%B4%EC%9C%84%ED%82%A4:Common.css) 로 옮길 수 있도록 서버에서는 삭제하면 좋을 것 같습니다.

감사합니다.

**Comment by choidamdam** [comment]
배포 완료:
https://github.com/femiwiki/femiwiki.com/releases/tag/20180428-r1
