### ISSUE TITLE
편집기 '사소한 편집'에 도움말 링크

### ISSUE THREAD

**Issue by vvvvviral** [femiwiki/docker-mediawiki#85]
관련 요청: https://femiwiki.com/w/주제:Tvo8q709ux0xsnbr

편집기 하단의 '사소한 편집'에 도움말(https://femiwiki.com/w/도움말:사소한_편집)을 링크하면 실수하는 분들 또는 사소한 편집이 무엇인지 궁금한 분들이 더 보기 편할 것 같습니다.

**Comment by lens0021** [comment]
시험삼아서 [미디어위키:Minoredit](https://femiwiki.com/w/%EB%AF%B8%EB%94%94%EC%96%B4%EC%9C%84%ED%82%A4:Minoredit)‎‎에 링크만 넣어 봤는데 링크가 새 창으로 안 뜨고 현재창으로 뜨려고 하면서 편집을 버리겠느냐는 확인창이 나옵니다, 링크에 새 창으로 뜨게 하는 처리가 필요해 보입니다.

**Comment by paikwiki** [comment]
"[미디어위키:Copyrightwarning](https://femiwiki.com/w/mediawiki:Copyrightwarning)"에 "[도움말:사소한 편집](https://femiwiki.com/w/%EB%8F%84%EC%9B%80%EB%A7%90:%EC%82%AC%EC%86%8C%ED%95%9C_%ED%8E%B8%EC%A7%91)"을 끼워넣고 접힌 테이블을 이용하면 어떨까요? "도움말:사소한 편집"의 내용 중에서 문서 저장 버튼 하단에 보여줄 부분만 `<onlyinclude>` 태그로 지정해주면 좋을 것 같습니다.

적용한 예제는 "[사용자:Paikwiki/테스트-Copyrightwarning](https://femiwiki.com/w/%EC%82%AC%EC%9A%A9%EC%9E%90:Paikwiki/%ED%85%8C%EC%8A%A4%ED%8A%B8-Copyrightwarning)"에서 확인하실 수 있습니다. "[미디어위키:Copyrightwarning](https://femiwiki.com/w/mediawiki:Copyrightwarning)"과 비교해보세요.

("[사용자:Paikwiki/테스트-Copyrightwarning](https://femiwiki.com/w/%EC%82%AC%EC%9A%A9%EC%9E%90:Paikwiki/%ED%85%8C%EC%8A%A4%ED%8A%B8-Copyrightwarning)"는 당분간만 유지하고 지울 것이므로 기록을 위해 스샷첨부합니다.)

![2018-09-13 00 46 43](https://user-images.githubusercontent.com/4120850/45436871-b92ce900-b6ee-11e8-9532-051df20be021.jpg)
![2018-09-13 00 46 47](https://user-images.githubusercontent.com/4120850/45436873-b9c57f80-b6ee-11e8-9396-3e2bb84913c6.jpg)

**Comment by paikwiki** [comment]
테이블의 가로 길이를 100% 지정했는데 오히려 안좋은 방법인 거 같기도 하네요. "[펼치기]" 대신 "[더알아보기]"같은 문구로 바꾸고 테이블 테두리 선과 배경색을 없애서 텍스트만 보이게 스타일을 변경해도 좋을 것 같습니다.

**Comment by lens0021** [comment]
테스트를 해봤는데, 일반 편집창에서는 펼치기 숨기기가 작동하지만 시각편집기의 "바뀐 내용 저장하기"창에서는 작동하지 않습니다.

그보다 제가 적당히 수정한 다음에 [주제:Tvo8q709ux0xsnbr](https://femiwiki.com/w/%EC%A3%BC%EC%A0%9C:Tvo8q709ux0xsnbr)에서는 해결됐다고 적고 닫았었는데 여기 이슈는 닫질 않았었나 보네요 :sweat_smile:

**Comment by paikwiki** [comment]
네 해결됐다고 쓰신 건 봤는데, 편집을 한 후에  “사소한 편집이 무엇인가요?”를 클릭했을 때 창을 이동하겠냐는 알림창이 뜨더라구요. 개선이 필요할 것 같아 고민을 했는데 시각편집기에서 문제가 있다면 다른 방법을 찾아야겠네요. 큰 문제는 아니니 이슈를 닫으셔도 무방할 것 같습니다.
