### ISSUE TITLE
신규 사용자의 편집 권한 지연

### ISSUE THREAD

**Issue by minortriad** [femiwiki/docker-mediawiki#88]
반달의 증가로 인해, 신규 사용자에게 편집 권한 주는 것을 지연하는 방법에 대해 논의되었습니다.

**Comment by minortriad** [comment]
#89 에서처럼 Autoconfirmed user group 의 시간 조건을 이용하여 편집 권한을 지연하기로 하였습니다.

**Comment by choidamdam** [comment]
완료된 이슈입니다.
