### ISSUE TITLE
Realnames 확장 사용 시 실명 노출 문제

### ISSUE THREAD

**Issue by choidamdam** [femiwiki/docker-mediawiki#90]
기존에 이미 실명을 입력한 사용자의 경우 Realnames 확장 사용 시 실명 노출되는 문제에 대한 해결이 필요합니다.

**Comment by lens0021** [comment]
Realnames를 사용할 가능성이 매우 낮아짐에 따라 이슈를 닫았으면 합니다.

**Comment by choidamdam** [comment]
Realnames 확장은 사용하지 않는 것으로 진행되었으므로 이슈 닫습니다.
