### ISSUE TITLE
제재 절차 자동화

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#97]
[위키에 미리 작성한 글](https://femiwiki.com/w/%EC%A3%BC%EC%A0%9C:Tsqkf5q1y6z1ozdj)이 있습니다.

현재, 사용자 문서, 토론 문서, 특수:차단, 특수:이름바꾸기에서 나뉘어 이뤄지면서 진행 과정과 숫자 계산을 모두 사람이 처리해야 하는 제재 절차를 자동화하고 통일할 필요가 있습니다.

**Comment by choidamdam** [comment]
배포 완료:
https://github.com/femiwiki/femiwiki.com/releases/tag/20180428-r1
